build:
	-gcc -Wfatal-errors -Wextra \
	-std=c11 \
	-I"C:\Users\eduar\Desktop\Programacao\C\trabalhoCG\libraries\include\cglm\include" \
	-L"C:\Users\eduar\Desktop\Programacao\C\trabalhoCG\libraries\include\cglm\win\Release" \
	-c */*.c \